# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 812dfb7121ed7ca88f427134232cb3cfd859df1a7fa4c28c1aa87fc38d4bb526e40bab2160dbae0e616f6c34fa44b90819ba64d9924ac2ae7328b6f7d11edc88

test:
  secret_key_base: 69c258d12b6773a021a9327dd864ddb97f8be59cc4a7f9c1d1dd7369032183f581aac1571385eb13f0cc67f0a24aff2dd6dcfc796308fe816f94d431577ee949

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
